# Generated by Django 4.1.7 on 2023-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
