# Generated by Django 4.1.7 on 2023-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifters', '0004_remove_userprofile_userid_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
