# Generated by Django 4.1.7 on 2023-03-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifters', '0005_alter_userprofile_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
