# Generated by Django 4.1.7 on 2023-03-18 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lifters', '0006_userprofile_height_userprofile_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalrecord',
            name='date_lifted',
        ),
        migrations.RemoveField(
            model_name='personalrecord',
            name='lift_name',
        ),
        migrations.RemoveField(
            model_name='personalrecord',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='personalrecord',
            name='weight_lifted',
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='benchpress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record'),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
