# Generated by Django 4.1.7 on 2023-03-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifters', '0007_remove_personalrecord_date_lifted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='metric',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
