# Generated by Django 4.1.7 on 2023-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifters', '0008_userprofile_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='lifters.userprofile'),
        ),
    ]
