# Generated by Django 4.1.7 on 2023-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifters', '0009_userprofile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='lifters.userprofile'),
        ),
    ]
