# Generated by Django 4.1.7 on 2023-07-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifters', '0010_remove_userprofile_following_userprofile_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalRecord',
        ),
    ]
