# Generated by Django 4.1.7 on 2023-07-17 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_record_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lifters', '0011_delete_personalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchpress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
