# Generated by Django 4.1.7 on 2023-03-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='body_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
