# Generated by Django 4.1.7 on 2023-03-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_body_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='lift_name',
            field=models.CharField(choices=[('BP', 'Benchpress'), ('SQ', 'Squat'), ('DL', 'Deadlift')], max_length=50),
        ),
    ]
