# Generated by Django 4.1.7 on 2023-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_lift_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='repetitions',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
