# Generated by Django 4.1.7 on 2023-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_repetitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='lift_name',
            field=models.CharField(choices=[('Benchpress', 'Benchpress'), ('Squat', 'Squat'), ('Deadlift', 'Deadlift')], max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight_lifted',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
