# Generated by Django 4.1.7 on 2023-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_lift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='weight_lifted',
            field=models.FloatField(),
        ),
    ]
