# Generated by Django 4.1.7 on 2023-07-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_record_weight_lifted'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
    ]
