# Generated by Django 4.1.7 on 2023-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_record_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='video_url',
        ),
        migrations.AddField(
            model_name='record',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
