# Generated by Django 4.1.7 on 2023-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_record_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images/videos/', verbose_name=''),
        ),
    ]
