# Generated by Django 4.1.7 on 2023-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='feed.post'),
        ),
    ]
