# Generated by Django 4.1.7 on 2023-08-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_feed_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
